In [ ]:
import tensorflow as tf
tf.test.gpu_device_name()

''

In [ ]:
import tensorflow as tf
tf.test.gpu_device_name()

'/device:GPU:0'

In [ ]:
import pandas as pd
import numpy as np
df=pd.DataFrame(np.random.randint(0,100,size=(65000,10000)))
print (df)

       0     1     2     3     4     5     6     7     8     9     ...  9990  \
0        19    90    66    43    66    31     8    63    85    43  ...     3   
1        29     2    29    66    97    26    48    96    17    16  ...    50   
2        93    96    54    84    34    97    72    68    39    32  ...    67   
3         8    89    85     2    53    36    20    92    37    60  ...    76   
4        91    39    10    51    25    59    55    61    72    80  ...    45   
...     ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
64995    60    39    13    14    24    17    74    70    11    24  ...    16   
64996    56    68    81    73    91    98    30    59    13    43  ...    25   
64997    55    98    73    35     1    92    23    56    99    21  ...    31   
64998    84    67    41    79    86    57    19    86    25    90  ...     7   
64999    30    23    28    45    92    90    82     5    64    90  ...    16   

       9991  9992  9993  9994  9995  99

In [ ]:

test_list = [[5, 8, 9], [2, 0, 9], [5, 4, 2], [2, 3, 9]]

print("The original list : " + str(test_list))

res = {test_list[0][ele] : test_list[ele + 1] for ele in range(len(test_list) - 1)}

print("The Assigned Matrix : " + str(res))


The original list : [[5, 8, 9], [2, 0, 9], [5, 4, 2], [2, 3, 9]]
The Assigned Matrix : {5: [2, 0, 9], 8: [5, 4, 2], 9: [2, 3, 9]}


In [ ]:
from itertools import groupby

test_list = [7, 4, 6, 7, 4, 2, 6, 4, 2]

print("original list : " + str(test_list))

res = [list(val) for key, val in groupby(sorted(test_list))]
		
print("Matrix in grouping : " + str(res))


original list : [7, 4, 6, 7, 4, 2, 6, 4, 2]
Matrix in grouping : [[2, 2], [4, 4, 4], [6, 6], [7, 7]]


In [ ]:
import numpy as np

A = np.array([[1, 9], [3, 4]])
  
B = np.array([[4, 8], [6, 2]])

print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)

print("Addition of two matrix")
print(np.add(A, B))

Printing elements of first matrix
[[1 9]
 [3 4]]
Printing elements of second matrix
[[4 8]
 [6 2]]
Addition of two matrix
[[ 5 17]
 [ 9  6]]


In [ ]:
import itertools

def sub_mat_even(n):
	
	temp = itertools.count(1)
	
	l = [[next(temp)for i in range(n)]for i in range(n)]
	
	if n%2 == 0:
		for i in range(0,len(l)):
			if i%2 == 1:
				l[i][:] = l[i][::-1]
	
	for i in range(n):
		for j in range(n):
			print(l[i][j],end=" ")
		print()

n = 4
sub_mat_even(n)


1 2 3 4 
8 7 6 5 
9 10 11 12 
16 15 14 13 


In [ ]:
tupMat = [[(7, 4, 9), (4, 1, 2)], [(9, 2, 6), (4, 1, 7)]]
additionVals = [7, 18]
print("Elements of Tuple matrix initially :" + str(tupMat))

addTupMat = [[sub + (additionVals[i], ) for sub in ele] for i, ele in enumerate(tupMat)]

print("Elements of Tuple matrix after addition :" + str(addTupMat))

Elements of Tuple matrix initially :[[(7, 4, 9), (4, 1, 2)], [(9, 2, 6), (4, 1, 7)]]
Elements of Tuple matrix after addition :[[(7, 4, 9, 7), (4, 1, 2, 7)], [(9, 2, 6, 18), (4, 1, 7, 18)]]
