Name : Anshita
 Roll no : 102003182
 Group : 3CO8

In [3]:
import numpy as np
import pandas as pd
from numpy import linalg as lin
from scipy.stats import mstats as st
import PIL.Image as Image

### Q1: Questions on Basic NumPy Array

In [14]:
arr=np.array([1, 2, 3, 6, 4, 5])

In [15]:
np.flip(arr,axis=0)

array([5, 4, 6, 3, 2, 1])

In [16]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])

In [17]:
array1.flatten()

array([1, 2, 3, 2, 4, 5, 1, 2, 3])

In [18]:
array1

array([[1, 2, 3],
       [2, 4, 5],
       [1, 2, 3]])

In [19]:
array1.ravel()

array([1, 2, 3, 2, 4, 5, 1, 2, 3])

In [20]:
array1


array([[1, 2, 3],
       [2, 4, 5],
       [1, 2, 3]])

In [24]:
arr1 = np.array([[1, 2], [3, 4]]) 
arr2 = np.array([[1, 2], [3, 4]])

In [26]:
np.array_equal(arr1,arr2)

True

In [27]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [31]:
st.mode(x)[0]

array([1.])

In [36]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

In [37]:
gfg.sum()

45

In [38]:
# Sum of all elements row-wise
gfg.sum(axis=1)

matrix([[14],
        [16],
        [15]])

In [39]:
# Sum of all elements column-wise
gfg.sum(axis=0)

matrix([[20,  9, 16]])

In [40]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])

In [41]:
# i. Sum of row elements
n_array.sum(axis=1)

array([ 95,  76, 133])

In [42]:
# ii. Sum of columns elements
n_array.sum(axis=0)

array([ 96, 114,  94])

In [43]:
# Sum of diagonal elements
n_array.trace()
# if want other diagonal transpose it using flip method

176

In [47]:
# Eigen values of matrix
lin.eig(n_array)[0]

array([98.16835147, 28.097044  , 49.73460452])

In [48]:
# Eigen vectors of matrix
lin.eig(n_array)[1]

array([[ 0.4574917 ,  0.34637121, -0.15017693],
       [ 0.28447814, -0.72784061, -0.4852124 ],
       [ 0.84248058,  0.59184038,  0.8614034 ]])

In [49]:
# Inverse of matrix
lin.inv(n_array)

array([[ 0.02404141, -0.00911212, -0.00444671],
       [-0.01667882,  0.02966905,  0.0024785 ],
       [ 0.00631287, -0.01603732,  0.01217379]])

In [50]:
# Determinant of matrix
lin.det(n_array)

137180.0000000001

In [51]:
# Multiply the following matrices and also find covariance between matrices using NumPy:
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])
p*q

array([[ 4, 10],
       [12, 21]])

In [53]:
np.cov(p,q)

array([[0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5]])

In [68]:
p_1 = np.array([[1, 2], [2, 3], [4, 5]] )
q_1 = np.array([[4, 5, 1], [6, 7, 2]])
# p_2=np.array([[1,2,2],[3,4,5]])
# q_2=np.array([[5,2,2],[7,4,5]])
# print(p_2.shape)
# print(q_2.shape)
# p_1*q_1
lin.multi_dot([p_1,q_1])

array([[16, 19,  5],
       [26, 31,  8],
       [46, 55, 14]])

In [69]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

In [70]:
np.inner(x,y)

array([[17, 52],
       [13, 62]])

In [71]:
np.outer(x,y)

array([[ 2, 10,  0, 10, 20,  6],
       [ 3, 15,  0, 15, 30,  9],
       [ 4, 20,  0, 20, 40, 12],
       [ 3, 15,  0, 15, 30,  9],
       [ 2, 10,  0, 10, 20,  6],
       [ 9, 45,  0, 45, 90, 27]])

### Q2: Based on NumPy Mathematics and Statistics

In [73]:
ar = np.array([[1, -2, 3],[-4, 5, -6]]) 
# i. Find element-wise absolute value
np.abs(ar)

array([[1, 2, 3],
       [4, 5, 6]])

In [81]:
# ii.Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each row.
# Axis or axes along which the quantiles are computed. The default is to
# compute the quantile(s) along a flattened version of the array.
# row wise flattening

ar_r=ar.flatten()
# column wise flattening
ar_c=ar.flatten('F')
print("The 25% quantile",np.quantile(ar_r,0.25))
print("The 50% quantile",np.quantile(ar_r,0.50))
print("The 75% quantile",np.quantile(ar_r,0.75))
print(ar_r)
print(ar_c)

The 25% quantile -3.5
The 50% quantile -0.5
The 75% quantile 2.5
[ 1 -2  3 -4  5 -6]
[ 1 -4 -2  5  3 -6]


In [83]:
# for each row
print("The 25 percentile of each row is",np.quantile(ar,axis=1,q=0.25))
np.quantile(ar,axis=1,q=0.75)
np.quantile(ar,axis=1,q=0.5)

The 25 percentile of each row is [-0.5 -5. ]


array([ 1., -4.])

In [ ]:
# for each column
np.quantile(ar,axis=0,q=0.25)

In [104]:
# Mean, Median and Standard Deviation of flattened array, of each column, and each row

# Mean of flattened array
ar_r.mean()
# mean of array row wise
np.mean(ar,axis=1)
# mean of array column wise
print(np.mean(ar,axis=0))
# # Median
print(np.median(ar_r))
print(np.median(ar,axis=1))
print(np.median(ar,axis=0))
# # Mode
print(st.mode(ar_r))
print(st.mode(ar,axis=1))
print(st.mode(ar,axis=0))
# st.mode(ar_r)[0]

ModeResult(mode=array([-6]), count=array([1]))
ModeResult(mode=masked_array(
  data=[[-2],
        [-6]],
  mask=False,
  fill_value=999999), count=masked_array(
  data=[[1],
        [1]],
  mask=False,
  fill_value=999999))
ModeResult(mode=masked_array(data=[[-4, -2, -6]],
             mask=False,
       fill_value=999999), count=masked_array(data=[[1, 1, 1]],
             mask=False,
       fill_value=999999))


In [106]:
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
np.floor(a)

array([-2., -2., -1.,  0.,  1.,  1.,  3.])

In [108]:
np.ceil(a)

array([-1., -1., -0.,  1.,  2.,  2.,  3.])

In [109]:
np.trunc(a)

array([-1., -1., -0.,  0.,  1.,  1.,  3.])

In [110]:
np.round(a)

array([-2., -2., -0.,  0.,  2.,  2.,  3.])

In [111]:
u = np.array([10, 52, 62, 16, 16, 54, 453])

In [116]:
# i. Sorted array
# OR np.sort()
u.sort()
u

array([ 10,  16,  16,  52,  54,  62, 453])

In [139]:
# ii. indices of sorted array
np.argsort(u)

array([0, 1, 2, 3, 4, 5, 6], dtype=int64)

In [118]:
# 4 smallest elements
u[:4]

array([10, 16, 16, 52])

In [120]:
u.sort(axis=-1)
u[:5]

array([10, 16, 16, 52, 54])

In [15]:
s = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
# i. Integer elements only
# len(s)
# if type(s[i])=='int'

int_arr=[i for i in range(len(s)) if type(s[i])==np.int64 ]
int_arr

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[]

In [12]:
[i for i in range(len(s)) if type(s[i])==np.float64]

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[0, 1, 2, 3, 4, 5]

### Q3.Write a function named img_to_array(path) that reads an image from a specified path and save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale images)

In [135]:

def is_grey_scale(img_path):
    img = Image.open(img_path).convert('RGB')
    w, h = img.size
    for i in range(w):
        for j in range(h):
            r, g, b = img.getpixel((i,j))
            if r != g != b: 
                return False
    return True


In [136]:
is_grey_scale("C:/Users/sajee/OneDrive/Pictures/IMG_3267.PNG")

False

In [138]:
is_grey_scale("C:/Users/sajee/gray.png")

True

In [ ]:
# (b) Load the saved file into jupyter notebook?

In [ ]:
# doubts
# 1.Cartesian product
# 2.save image in text file
# 3.